#!/bin/bash
git add .
git commit -m 'I created a git push script for more C pointers and it did this for me'
git push https://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@github.com/Runejnr/alx-low_level_programming.git
